### ISSUE TITLE
Cache latest release when the network is unavailable

### ISSUE THREAD

**Issue by mhanberg** [elixir-tools/elixir-tools.vscode#25]
Basically, [this](https://github.com/elixir-tools/elixir-tools.nvim/pull/130/files) functionality from elixir-tools.nvim should be ported over to elixir-tools.vscode.

**Comment by CoderDennis** [comment]
@mhanberg I'm looking at this one and I just wanted to confirm my understanding. `latestRelease` just gets the version string. It's not actually downloading the latest binary. Is that right? 

If so, then I don't understand why we need to do that. Shouldn't the version string just match the binary that we're using? What's the purpose of fetching the latest version string when we aren't getting the matching binary for that release?

**Comment by mhanberg** [comment]
> I'm looking at this one and I just wanted to confirm my understanding (or lack of it). latestRelease just gets the version string. It's not actually downloading the latest binary. Is that right?

This is correct

> Shouldn't the version string just match the binary deployed with the extension?

The extension is designed so that it will automatically install the latest versions of Next LS and Credo Language Server, without me having to release a new version of the extension.

There isn't really a binary deployed with the extension, it is a bootstrapping script that will run Mix.install with the release version fetched from the GitHub API.

**Comment by CoderDennis** [comment]
Oh! That makes sense. Thanks!

**Comment by mhanberg** [comment]
No longer relevant for NextLS
