### ISSUE TITLE
HEEx template formatting not working

### ISSUE THREAD

**Issue by crbelaus** [elixir-tools/elixir-tools.vscode#31]
I am trying next-ls and so far it is working great even though it is still in heavy development mode.\
One thing that I've noticed is that, while it formats the .ex and .exs files automatically, it does not format the .heex files.

When using elixir-ls I have this configuration that does the trick:

```json
  "[phoenix-heex]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "JakeBecker.elixir-ls"
  },
```

If I change the default formatter to the next-ls one it doesn't seem to do anything:

```json
  "[phoenix-heex]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "elixir-tools.elixir-tools"
  },
```

Am I doing something wrong? Or is it just that HEEx is not yet supported in the current development phase?

**Comment by mhanberg** [comment]
I think it's not supported. 

This must have slipped by me because we use sigils mostly at working for Surface templates. 

Should be an easy addition tho to have the extension activate on heex and surface files. 

I would just need to make sure it wouldn't need an actual next ls change.
