### ISSUE TITLE
`elixir` not found in `/usr/bin` when using `asdf` 

### ISSUE THREAD

**Issue by VictorGaiva** [elixir-tools/elixir-tools.vscode#32]
With the following `asdf` versions

```
erlang 26.0.2
elixir 1.15.2-otp-26
nodejs 16.19.1
```

## Problem
The VSCode extension fails to start since it looks for the Elixir instalation on `/usr/bin` folder, but asdf installs it on `$HOME/.asdf/shims/`.

## Solution

Either add `$HOME/.asdf/shims` to the search path for the binaries, or add a VSCode Setting to allow a user to manually override the `/usr/bin` prefix

**Comment by mhanberg** [comment]
A workout is to open VSCode with `code .` from the directory of your project. it then inherits the environment variables, including the path

**Comment by Cthuflu** [comment]
Note: source asdf from `~/.profile` instead of `~/.bashrc` to make sure the binaries are available for the environment. This will update the PATH for programs like vscode.

    source "$HOME/.asdf/asdf.sh"
