### ISSUE TITLE
Installed extension on VSCode 1.81.1, but nothing happens

### ISSUE THREAD

**Issue by dkulchenko** [elixir-tools/elixir-tools.vscode#49]
macOS 13.5.1 (ARM), VSCode 1.81.1, elixir-tools.vscode 0.7.0

I'm not sure if I messed something up, but I installed the extension (uninstalled all other Elixir extensions), restarted VSCode, but I don't see anything happening on any of my Elixir projects - no .elixir-tools directory being created, no Credo or Elixir options in the Output dropdown. I turned on the NextLS option and same thing. It seems like nothing's running at all.

Did I miss some sort of setup?

**Comment by dkulchenko** [comment]
It looks like *something* is happening, because Elixir syntax highlighting is not present before the extension install, but is present after.

Also, this is the only logs regarding the extension that I see in the extension host:

`2023-08-22 08:48:00.638 [info] ExtensionService#_doActivateExtension elixir-tools.elixir-tools, startup: false, activationEvent: 'onLanguage:elixir'`

**Comment by mhanberg** [comment]
were you ever prompted to install Next LS? (after enabling it in the setting)

**Comment by mhanberg** [comment]
Can you confirm there is nothing in `~/.cache/elixir-tools/nextls/bin`

**Comment by dkulchenko** [comment]
Confirmed - I have no `~/.cache/elixir-tools` directory.

**Comment by mhanberg** [comment]
This is very odd, let me try a clean installation to seem if I can reproduce.

one more question tho, how are you opening the projects? are you opening a folder at the root of the project? or are you openeing a folder of many projects and then opening a file in one of them

**Comment by dkulchenko** [comment]
Ah - that was it! My project is at app/ in my workspace, not at the root. Opening a fresh project at the root of the workspace showed the prompt and everything worked correctly. Now that I think about it, I did have to tell ElixirLS where my project root was in its extension settings.

Can close the issue if this is expected behavior.

**Comment by mhanberg** [comment]
roger!

Next LS supports Workspaces, so if you want you can add all of your projects to a workspace, and then open that workspace (this creates a workspace file)

you can also do `code --add ./app1 --add ./app2 --add ./app3` from the command line to create an adhoc workspace`
