### ISSUE TITLE
doesn't work on VSCode 1.78

### ISSUE THREAD

**Issue by epinault** [elixir-tools/elixir-tools.vscode#5]
I am playing with this but I am not sure if it s working or not. does it handle having a .credo file in my repo that configure the check I am interested in?

**Comment by epinault** [comment]
I don t see any of those warnings. I saw them earlier but upon restart it was not showing at all. But I had some message before I restarted that it could not talk to Credo Backend or something like that 

I have

ersion: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z (20 hrs ago)
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes

and

Name: elixir-tools.vscode
Id: elixir-tools.elixir-tools
Description: Elixir extension for VSCode.
Version: 0.0.4
Publisher: elixir-tools
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=elixir-tools.elixir-tools

**Comment by mhanberg** [comment]
Does `mix credo` show any warnings?

**Comment by epinault** [comment]
so I have multiple project opened and I have one I know has warning loaded within those project so I was hoping to see the warnings. those are Readability section though 

```
┃ [R] ↘ Avoid grouping aliases in '{ ... }'; please specify one fully-qualified alias per line.
┃ [R] ↘ Avoid grouping aliases in '{ ... }'; please specify one fully-qualified alias per line.
┃ [R] ↘ use must appear before defstruct
┃ [R] ↘ use must appear before defstruct
┃ [R] ↘ moduledoc must appear before alias
```

**Comment by mhanberg** [comment]
Multiple in the same VSCode window?

Are you using workspaces?

Are these umbrella apps?

Or a mono repo?

**Comment by epinault** [comment]
> Multiple in the same VSCode window?

yes. I have open multiple folder to the same workspace

-> Are you using workspaces?
I have one workspace with different project that are related but separate app/lib

-> Are these umbrella apps?
nope. All regular app or libs

-> Or a mono repo?
nope, just separate folders

**Comment by mhanberg** [comment]
I think this is related to the 1.78 release of VSCode. 

Will hopefully have a fix out tonight.

**Comment by epinault** [comment]
awesome! I am excited to see this working

**Comment by mhanberg** [comment]
0.0.5 should hit the marketplace in the next 10 minutes.

please update and give it a try when you get a chance, thanks!

**Comment by mhanberg** [comment]
Can you try quitting and restarting vscode?

**Comment by mhanberg** [comment]
I think it might time out while it compiles the LSP, but when you restart it starts immediately. 

I'm still getting my bearings when it comes to developing vscode extensions.

**Comment by epinault** [comment]
I restarted it but not sure what I am suppose to see. I see file with credo check fialing but nothing visibile in that file?

**Comment by epinault** [comment]
ok I see ... under a function i that the expected behavior? once I over it shows the actually warniing .But thought it would show color based or more visible

**Comment by mhanberg** [comment]
Yeah I think that is because vscode only shows squiggles for errors and warnings, not hints. 

And also credo only gives you the starting position in the document for the diagnostic, so in neovim it only underlines a single character.
