### ISSUE TITLE
H_sigil templates aren't being formatted

### ISSUE THREAD

**Issue by AHBruns** [elixir-tools/elixir-tools.vscode#65]
I mean, the title kind says it all. The rest of my files are being formatted on save, but my H_sigil templates just aren't. I ran mix format to make sure it wasn't something I'd done, and that worked fine. Additionally, I explicitly had vscode format the document and that didn't do anything. Looking in the NexLS logs, there's no errors. Let me know what I can do to help debugging.

**Comment by mhanberg** [comment]
Try updating your elixir version. 

This was happening to me recently and it turned out there was a formatted bug that was fixed in 1.15.6 or 1.16.7

**Comment by AHBruns** [comment]
Worked like a charm. Thank you for the help. Sorry for the bother!
