### ISSUE TITLE
Settings for Credo Extension

### ISSUE THREAD

**Issue by tensiondriven** [elixir-tools/elixir-tools.vscode#67]
In [next-ls/288](https://github.com/elixir-tools/next-ls/issues/288) users are describing an issue wherein credo rules are applied whenever the runtime environment has credo loaded (via mix.exs).  There are many cases where a project uses credo, but runs it with different command line options than the defaults.

Since next-ls will load credo and run with a fixed set of arguments, and since there's no way to conditionally change this on each developers system, it leaves developers in a precarious situation wherein they have no way to disable the sometimes thousands of credo warnings.

Longer term, more configuration can be added to allow passing specific flags to credo.  

As a short-term solution, can we expose a [configuration variable](https://github.com/elixir-tools/elixir-tools.vscode/blob/main/package.json#L40) to disable credo entirely in next-ls?  (Not to disable Credo Language Server, but to disable next-ls's credo checking entirely?)

This would require updating both `elixir-tools.vscode` and `next-ls`, but it would solve a severe ergonomics issue, which is holding back adoption of elixir-tools.  (On my team, several people have tried switching from ElixirLS to elixir-tools, but then switched back, thinking it wasn't ready for prime-time.  In my personal experience, this inability to disable credo entirely is the only issue that really hampers my use of elixir-tools/elixir-ls.)

**Comment by mhanberg** [comment]
We can group this into https://github.com/elixir-tools/next-ls/issues/288 as one of the configuration options.

**Comment by mhanberg** [comment]
Blocked on https://github.com/elixir-tools/next-ls/issues/288
