### ISSUE TITLE
Provide a way to restart next-ls without leaving VScode

### ISSUE THREAD

**Issue by NobbZ** [elixir-tools/elixir-tools.vscode#93]
To mitigate after a crash (see elixir-tools/next-ls#517) I have to manually close and restart VScode to restart the LSP.

There should be an easier way to restart NextLS without having to clsoe VSCode.

**Comment by mhanberg** [comment]
you can run `Developer: Reload Window` from the command palette and it will effectively do that.

**Comment by NobbZ** [comment]
I will try that on the next crash
