### ISSUE TITLE
Invalid `Content-Length` property enabling Credo

### ISSUE THREAD

**Issue by rvonzimr** [elixir-tools/elixir-tools.vscode#94]
Whenever I attempt to enable Credo on my application, I get spammed with notifications all mentioning an invalid `Content-Length` property from `jsonrpc`. The actual messages being logged appear to be warnings when compiling the app, but nothing broken.

Here's a snipped of the extension output:
```
[Error - 11:16:36 AM] Client Credo: connection to server is erroring.
Header must provide a Content-Length property.
{"{\"jsonrpc\"":"\"2.0\",\"method\":\"window/logMessage\",\"params\":{\"message\":\"warning: redefining module Conversation.Graph.Node.Processor.Upload (current version loaded from /home/[redacted]/git/project/core/.elixir-tools/_build/dev/lib/conversation/ebin/Elixir.Conversation.Graph.Node.Processor.Upload.beam)\\n  lib/conversation/graph/node/processor/upload.ex:1: Conversation.Graph.Node.Processor.Upload (module)\",\"type\":4}}Content-Length: 350"}
Shutting down server.
```
nextls version:
```
./nextls --version
0.23.0
```

**Comment by rvonzimr** [comment]
Ah! just saw this was disabled by default as next supports credo itself? Maybe I can safely ignore this then :grin:

**Comment by mhanberg** [comment]
I'm not really sure what this is, but I am going to archive the credo language server soon, as Next LS has credo support
