### ISSUE TITLE
(RuntimeError) Failed to parse!

### ISSUE THREAD

**Issue by davemccrea** [elixir-tools/elixir-tools.vscode#96]
Hi!

I am getting the following error:

```
[Error - 14:20:41] ** (RuntimeError) Failed to parse!
    (next_ls 0.23.1) lib/next_ls/document_symbol.ex:31: NextLS.DocumentSymbol.fetch/1
    (next_ls 0.23.1) lib/next_ls.ex:253: NextLS.handle_request/2
    (gen_lsp 0.10.0) lib/gen_lsp.ex:350: anonymous fn/2 in GenLSP.loop/3
    (telemetry 1.2.1) /home/mitchell/src/next-ls/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (gen_lsp 0.10.0) lib/gen_lsp.ex:349: anonymous fn/7 in GenLSP.loop/3
    (gen_lsp 0.10.0) lib/gen_lsp.ex:553: GenLSP.attempt/4
    (stdlib 6.0) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

On the following system:

- elixir-tools 0.15.1
- VSCode 1.90.2
- Fedora Linux 40.20240701.0 (Silverblue)
- Elixir 1.17.1 on OTP 26 installed with asdf

The error seems to occur when autocomplete kicks in. Syntax highlighting, formatting, go to defintion, etc work. 

I can use elixir-tools with Neovim without any issue.

**Comment by mhanberg** [comment]
It just prints that when it tries to parse incomplete source code when calculating things like document symbols.

**Comment by davemccrea** [comment]
I see! I thought it had something to do with the lack of completions but I enabled them in the VSCode settings and everything is working as expected. Thanks!
